### ISSUE TITLE
Can you provide some detail about how to build this plugin with caddy? 

### ISSUE THREAD

**Issue by messyidea** [hacdias/filemanager-old#101]
Hi,

At last issue, with your help, this memory problem has fixed.
I want the newest plugin, but the offical caddy website have not update.
So I want to build it by myself, but I have met some problems now.

I followed this [tutorial](https://github.com/mholt/caddy/wiki/Extending-Caddy) and some commands at [travis-ci](https://travis-ci.org/hacdias/filemanager). Finally I got a binary about caddy.
But when I execute it, I see the error: "could not locate box "./assets/dist""
It seems that some assets are not properly compiled.
As I have little knowledge about js and babel, I can not continue to build it.

Can you provide some detail about how to build this plugin when you are free?
Thank you~

**Comment by hacdias** [comment]
Hello @messyidea!

I'm doing a complete rework on this plugin and the new version will be out soon and I'll leave the instructions afterwards.

But if this is a urgent thing, I can write them today.

**Comment by messyidea** [comment]
Hi,
It's not very urgent to me now. 
Just finish your own work first :)
Thank you ~

**Comment by hacdias** [comment]
I'll leave more information afterwards, but try building 465b10a the way you did before. It should work.

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#132
