### ISSUE TITLE
more grid types & slideshow mode!

### ISSUE THREAD

**Issue by nwgat** [hacdias/filemanager-old#41]
a album grid with sideshow would have been nice. 
also there is alot of wasted space on the sides, whats up with that?

**Comment by hacdias** [comment]
Tell me what would you change! 😃

**Comment by hacdias** [comment]
Pinging @nwgat

**Comment by hacdias** [comment]
By the way, you can incorporate styles if you want @nwgat using the option `styles`.

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#129
