### ISSUE TITLE
Using webdav to upload large files

### ISSUE THREAD

**Issue by isdamir** [hacdias/filemanager-old#90]
Using webdav to upload large files takes up memory equal to the size of the file, and the upload speed is very unstable.

**Comment by isdamir** [comment]
i found some link:
https://github.com/mholt/caddy/issues/1310
https://github.com/mholt/caddy/pull/1314/commits/8048e9c3bc35572a296ad86fd556787bd0dab617

but not work in caddy-filemanager

**Comment by hacdias** [comment]
Hello @isdamir! Right now I'm using Golang's official [webdav package](https://godoc.org/golang.org/x/net/webdav) so I can't do much about it. Although, I'm not sure if it's related to `webdav` package or Caddy itself. Do you know anything about this @mholt?

**Comment by mholt** [comment]
No clue. Some profiling would be needed to figure out why it's using a lot of memory.

**Comment by isdamir** [comment]
OK, I try to debug, have more information and then feedback.

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#139
